# default pipeline build, client should already have existing pipeline. ​

trigger:​
  branches:​
    include:​
    - '*' ​

pool:​
  vmImage: ubuntu-latest​

steps:​
- script: echo Veracode Internal Basic Pipeline​ trigger
  displayName: 'Veracode Internal Basic Pipeline trigger'