# Basic pipeline to trigger a Veracode scan

trigger:
  branches:
    include:
    - '*' 

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Veracode trigger
  displayName: 'Veracode Pipeline Trigger'